name: Test-Build
on:
  push:
    branches:
      - main
jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Make Directory for results
        run: mkdir -p testResults

      - name: Run POSTMAN collection
        run: |
          newman run petstore.collection.json -r htmlextra --reporter-htmlextra-export testResults/htmlreport.html --reporter-htmlextra-darkTheme > testResults/runreport1.html

      - name: List files in testResults
        run: ls -la testResults

      - name: Check testResults directory
        run: |
          echo "Contents of testResults:"
          ls -la testResults
          echo "Contents of runreport1.html:"
          cat testResults/runreport1.html

      - name: Upload the contents of Test Results directory to workspace
        uses: actions/upload-artifact@v2
        with:
          name: RunReports
          path: testResults/
