name: Test-Build
on:
  push:
    branches:
      - main
jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Make Directory for results
        run: mkdir -p testResults

      - name: Run POSTMAN collection
        run: |
          newman run petstore.collection.json -r htmlextra --reporter-htmlextra-export testResults/htmlreport.html --reporter-htmlextra-darkTheme > testResults/runreport1.html 2>&1

      - name: Check newman run output
        run: |
          echo "Newman run output:"
          cat testResults/runreport1.html || echo "File runreport1.html not found"

      - name: Upload the contents of Test Results directory to workspace
        uses: actions/upload-artifact@v2
        with:
          name: RunReports
          path: testResults/
