# # name: Test-Build
# # on:
# #   push:
# #     branches:
# #       - main
# # jobs:
# #   test-api:
# #     runs-on: ubuntu-latest
# #     steps:
# #       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
# #       - uses: actions/checkout@v2

# #       # INstall Node on the runner
# #       - name: Install Node
# #         uses: actions/setup-node@v1
# #         with:
# #           node-version: "16.x"

# #       # Install the newman command line utility and also install the html extra reporter
# #       - name: Install newman
# #         run: |
# #           npm install -g newman
# #           npm install -g newman-reporter-htmlextra

# #       # Make directory to upload the test results
# #       - name: Make Directory for results
# #         run: mkdir -p testResults

# #       # Run the POSTMAN collection
# #       - name: Run POSTMAN collection
# #         run: |
# #           newman run petstore.collection.json -r htmlextra --reporter-htmlextra-export testResults/htmlreport.html --reporter-htmlextra-darkTheme  > testResults/runreport1.html
# #         continue-on-error: true

# #       # Upload the contents of Test Results directory to workspace
# #       - name: Output the run Details
# #         uses: actions/upload-artifact@v2
# #         with:
# #           name: RunReports
# #           path: testResults

# name: Test-Build
# on:
#   push:
#     branches:
#       - main
# jobs:
#   test-api:
#     runs-on: ubuntu-latest
#     steps:
#       # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
#       - uses: actions/checkout@v2

#       # Install Node on the runner
#       - name: Install Node
#         uses: actions/setup-node@v1
#         with:
#           node-version: "16.x"

#       # Install the newman command line utility and also install the html extra reporter
#       - name: Install newman
#         run: |
#           npm install -g newman
#           npm install -g newman-reporter-htmlextra

#       # Make directory to upload the test results
#       - name: Make Directory for results
#         run: mkdir -p testResults

#       # Run the POSTMAN collection
#       - name: Run POSTMAN collection
#         run: |
#           newman run petstore.collection.json -r htmlextra --reporter-htmlextra-export testResults/htmlreport.html --reporter-htmlextra-darkTheme > testResults/runreport1.html
#         continue-on-error: true

#       # Upload the contents of Test Results directory to workspace
#       - name: Output the run Details
#         uses: actions/upload-artifact@v2
#         with:
#           name: RunReports
#           path: testResults

#       - name: Download the test results artifact
#         uses: actions/download-artifact@v2
#         with:
#           name: RunReports

#       # Create a directory in the repo and copy test results there
#       - name: Copy test results to repo
#         run: |
#           mkdir -p results
#           cp -r testResults/* results/
#           ls -al results

#       # Commit and push the results to the repo
#       - name: Commit and push results
#         run: |
#           git config user.name "github-actions"
#           git config user.email "actions@github.com"
#           git add results
#           git commit -m "Add test results"
#           git push origin main

name: Test-Build
on:
  push:
    branches:
      - main
jobs:
  test-api:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Install Node on the runner
      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      # Install the newman command line utility and also install the html extra reporter
      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      # Make directory to upload the test results
      - name: Make Directory for results
        run: mkdir -p testResults

      # Run the POSTMAN collection
      - name: Run POSTMAN collection
        run: |
          newman run petstore.collection.json -r htmlextra --reporter-htmlextra-export testResults/htmlreport.html --reporter-htmlextra-darkTheme > testResults/runreport1.html
        continue-on-error: true

      # Output the contents of Test Results directory to verify results
      - name: List test results
        run: ls -al testResults

      # Upload the contents of Test Results directory to workspace
      - name: Output the run Details
        uses: actions/upload-artifact@v2
        with:
          name: RunReports
          path: testResults

      # Download the test results artifact
      - name: Download the test results artifact
        uses: actions/download-artifact@v2
        with:
          name: RunReports

      # Create a directory in the repo and copy test results there
      - name: Copy test results to repo
        run: |
          cp -r testResults/* ./
          ls -al

      # Commit and push the results to the repo
      - name: Commit and push results
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add htmlreport.html
          git commit -m "Add test results"
          git push origin main
